# Use a imagem base do MySQL
FROM mysql:latest

# Defina variáveis de ambiente para configurar o MySQL
ENV MYSQL_ROOT_PASSWORD=root
ENV MYSQL_DATABASE=electron
ENV MYSQL_USER=root
ENV MYSQL_PASSWORD=root

# Copie o script SQL para inicializar o banco de dados
COPY init.sql /docker-entrypoint-initdb.d/