version: '3'
services:
  mysql:
    image: mysql:latest
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: Newpass$1972
      MYSQL_DATABASE: projeto_electron
      MYSQL_USER: bia
      MYSQL_PASSWORD: Newpass$1972
    ports:
      - "3307:3306"
