version: '3.8'

services:
  node-server:
    build: .
    restart: always
    ports:
      - "3000:3000"
    depends_on:
      - mysql


  mysql:
    image: mysql:latest
    container_name: node-mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: electron_db
      MYSQL_PASSWORD: root
    volumes:
      - mysql-data:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    container_name: node-phpmyadmin
    restart: unless-stopped
    ports:
      - '8081:80'
    environment:
      PMA_ARBITRARY: 1
      PMA_HOST: mysql
      PMA_USER: root
      PMA_PASSWORD: root

volumes:
  mysql-data:
