version: '3'

services:
  mysql:
    image: mysql:latest
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: electron
      MYSQL_USER: root
      MYSQL_PASSWORD: root
    ports:
      - "3306:3306"  

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    restart: always
    ports:
      - "8081:8081"  
    environment:
      PMA_HOST: mysql
      MYSQL_ROOT_PASSWORD: root_password

  electron_app:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - mysql
    ports:
      - "8080:8080"
    volumes:
      - ./app:/app
